apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: workdaemonset
  labels:
    app: guestbook
    tier: workdaemonset
spec:
  template:
    metadata:
      labels:
        tier: workdaemonset
    spec:
      hostPID: true
      containers:
        - name: hostvm-configurer-container
          image: gcr.io/google-containers/startup-script:v1
          securityContext:
            privileged: true
          env:
            - name: STARTUP_SCRIPT
              value: |
                #! /bin/bash
                set -o errexit
                set -o pipefail
                set -o nounset

                # Disable hugepages
                echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
                echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
  selector:
    matchLabels:
      tier: workdaemonset